(* ::Package:: *)

(* ::Input:: *)
(*BeginPackage["Model"]*)
(**)
(*Document[d_]["Add"[newData_]] := Document[Append[d, newData]];*)
(*Document[d_]["Delete"[name_]]:=Document[Delete[d, Key[name]]]*)
(*Document[d_]["Set"[name_, newData_]]:=Document[Insert[d,name->newData, Key[name]]];*)
(*Document[d_]["Get"[name_]]:=d[name];*)
(*Document[d_]["Print"[]] := d;*)
(**)
(*Model[db_]["Get"[]] := db;*)
(*Model[db_]["Get"[name_]] := db[name];*)
(*Model[db_]["Get"[name_, field_]] := db[name]["Get"[field]];*)
(*Model[db_]["CreateDocument"[name_]] := Model[Append[db,<|*)
(*name->Document[Dataset[<||>]]*)
(*|>]];*)
(*Model[db_]["Add"[name_, d_]] := With[{old=db[name]},*)
(*Model[Append[Delete[db, name],<|name->old["Add"[d]]|>]]];*)
(*Model[db_]["DeleteDocument"[name_]]:=Model[Delete[db, name]];*)
(*Model[db_]["Delete"[doc_,name_]]:= With[{old=db[doc]},*)
(*Model[Append[Delete[db, doc],<|doc->old["Delete"[name]]|>]]];*)
(*Model[db_]["Set"[doc_,name_,newData_]]:=With[{old=db[doc]},*)
(*Model[Append[Delete[db, doc],<|doc->old["Set"[name, newData]]|>]]];*)
(*Model[db_]["UpdateDocument"[doc_, newDoc_]]:=Model[Insert[db,doc->newDoc,Key[doc]]];*)
(**)
(*EndPackage[]*)
(**)
(*(*tests*)
(*MyModel = Model[Dataset[<||>]];*)
(*  MyModel = MyModel["CreateDocument"["MyDocument"]];*)
(*  MyModel = MyModel["CreateDocument"["2ndDocument"]];*)
(**)
(*  MyModel=MyModel["Add"["MyDocument", <|a\[Rule]b|>]];*)
(*  MyModel=MyModel["Add"["MyDocument", <|c\[Rule]d, "e"\[Rule]Dataset[<|f\[Rule]g,h\[Rule]i|>]|>]];*)
(*  MyModel=MyModel["Add"["2ndDocument", <|a\[Rule]b|>]];*)
(*  MyModel["Get"["MyDocument"]]["Print"[]]*)
(*MyModel=MyModel["Delete"["MyDocument",a]];*)
(*  MyModel["Get"["MyDocument"]]["Print"[]]*)
(*Doc = MyModel["Get"["MyDocument"]];*)
(*  Doc["Get"["e"]][Key[h]]*)
(*Doc = Doc["Set"["e", Dataset[<|j\[Rule]k|>]]];*)
(*  MyModel = MyModel["UpdateDocument"["MyDocument",Doc]];*)
(*  Doc["Print"[]]*)
(* MyModel["Get"["MyDocument"]]["Print"[]]*)
(**)*)



